### ISSUE TITLE
colors were not right for userInterfaceStyle: "light"

### ISSUE THREAD

**Issue by trevorpfiz** [mrzachnugent/rnr-ui-inspired-by-shadcn#8]
This seems like an expo cache issue.

I had `userInterfaceStyle: "light"` and when I was first using rnr-ui the colors for buttons for example were too light. I changed to `userInterfaceStyle: "dark"` and everything looked good. Changed back to `userInterfaceStyle: "light"` and all the colors were fine?

I had been running `expo start -c` with no impact. Not sure.

**Comment by mrzachnugent** [comment]
Not sure to understand the issue. What do you mean by "the colors for buttons for example were too light"? 

So the colors were too light when you first had `userInterfaceStyle: "light"`, then you switched it to `"dark"`, it worked well, and then you switched it back to `"light"` and it worked well?

Not sure about the expo caching issue but async-storage is used to persist the theme which might be causing the seemingly caching issue.

**Comment by trevorpfiz** [comment]
Hey, sorry for being so vague. Instead of black for a default variant the button was gray, and for destructive it was a pale red instead of what it should be. When I changed the global.css values the colors would change, but not be accurate to what they should be.

I didn't set up the theme provider, just set `userInterfaceStyle` and copied the components in.

**Comment by mrzachnugent** [comment]
The theme provider is for the navigation so it shouldn't be related.

It could be a [nativewind](https://github.com/marklawlor/nativewind) issue (it is still in beta), a difference in versions of dependencies, an issue with your tailwind config, or something else.

Please add a minimal-repoduction repo with the same issue or at the minimum your tailwind config, your css variables, the version of nativewind that you are using, and the code for your button that have the wrong theme.

**Comment by trevorpfiz** [comment]
the issue is definitely something with expo or nativewind. I can't reproduce it.
